//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDM_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ability
    {
        public int id { get; set; }
        public string abiltyName { get; set; }
        public string abilityType { get; set; }
        public Nullable<double> cooldown { get; set; }
        public Nullable<int> godId { get; set; }
    
        public virtual God God { get; set; }
    }
}
