//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDM_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmiteBuildEntities : DbContext
    {
        public SmiteBuildEntities()
            : base("name=SmiteBuildEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Ability { get; set; }
        public virtual DbSet<Build> Build { get; set; }
        public virtual DbSet<BuildItem> BuildItem { get; set; }
        public virtual DbSet<God> God { get; set; }
        public virtual DbSet<GodStat> GodStat { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemStat> ItemStat { get; set; }
        public virtual DbSet<Stat> Stat { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
